
= Customize Ubuntu 20.04 to run with vanilla GNOME and without snap

*This is no longer maintained as I am moving my desktops to another distribution*

Running all the scripts (or the "`runall.bash`" script) will install *vanilla GNOME*, *remove snap and snap packages*, and install packages according to my personal preferences.
Pick and chose scripts to suit your own needs.

Some manual steps are required. Earlier attempts of automating everything have led to complexity resulting in stagnation and difficulties to maintain across new versions of OS.
I tried to strike a balance between automation, simplicity and maintainability for future versions.

== Snapped
I understand the motivation behind the snap technology, but at this point in time, snap has issues that are too detrimental for my desktop workflow:
* short lived applications slower to start than I intend to use them (eg: GNOME Character Map)
* automatic upgrades (having to "delay" it, rather than just refresh whenever you are ready)
* a Ubuntu only technology

This was my attempt at removing snap from Ubuntu 20.04, which worked, but tunred out to be too difficult to add other software beyond the basic.
I have decided to move to other Linux distributions that don't have these issues and still have a wide variety of Software that can be easily installed.

== Why using Bash
It was a conscious decision to use GNU Bash as the programming language despite its many flaws for reasons which distinguish it from recent build systems:

* Bash is well known and an integral part of Linux systems. Anybody familiar with customizing Linux systems has already been exposed to Bash.

* Perennity: https://en.wikipedia.org/wiki/Bash_(Unix_shell)#History[Bash has been around for a long time, since 1988] (note: https://en.wikipedia.org/wiki/Linux#Creation[Linux was created in 1991]).
https://en.wikipedia.org/wiki/Lindy_effect[Lindy effect] predicts that it will be around for at least another 30 years.

== Basic setup
. Install Ubutnu 20.04

. Get files and unzip::

 cd /var/tmp
 wget https://github.com/dorfsmay/laptop-setup-ubuntu-20.04/archive/master.zip
 unzip master.zip

. Install everything 

 cd laptop-setup-ubuntu-20.04/idempotent
 ./runall.bash

. reboot

. Check manual steps in the https://github.com/dorfsmay/laptop-setup-ubuntu-18.04/tree/master/MANUAL-STEPS[MANUAL-STEPS] directory

== Regular updates

* update Ubuntu
. `sudo apt update`
. `sudo apt upgrade -y`
. reboot

