#!/bin/bash -e

# Add french azerty keybaord during login
sudo sed -ie 's/XKBLAYOUT=.*$/XKBLAYOUT=us,fr/' /etc/default/keyboard
sudo sed -ie 's/XKBVARIANT=.*$/XKBVARIANT=,azerty/' /etc/default/keyboard
# Add french azerty keybaord to user
gsettings set org.gnome.desktop.input-sources sources "[('xkb', 'us'), ('xkb', 'fr+azerty')]"

# Set keyboard per windows
gsettings set org.gnome.desktop.input-sources per-window true

