#!/bin/bash -e

# References:
# https://www.videolan.org/developers/libdvdcss.html
# https://help.ubuntu.com/community/RestrictedFormats/PlayingDVDs
# https://askubuntu.com/questions/1052993/how-to-install-libdvdcss-so-2-library-to-ubuntu-18-04

# DVD from ubuntu repos
sudo apt install -y libdvdnav4 libdvd-pkg regionset
# dpkg-reconfigure needs to be run after libdvd-pkg is installed
sudo dpkg-reconfigure libdvd-pkg


# extra packages
sudo apt install -y \
    gstreamer1.0-plugins-bad \
    gstreamer1.0-plugins-ugly \
    gstreamer1.0-tools \
    gstreamer1.0-libav \
    ogmtools \
    brasero \
    ffmpeg \
    x264 \
    vlc \
    ubuntu-restricted-extras

sudo apt upgrade -y
sudo apt autoremove

